version: '3.5'
services:
  server:
    network_mode: host
    container_name: https-server
    image: golang:1.20.1-bullseye
    volumes:
      - ./build/server:/server
    working_dir: /server
    command: bash -c "./scripts/generateServerCerts.sh && ./server.out"
    ports:
      - '5001:5001'
  client:
    container_name: https-client
    image: golang:1.20.1-bullseye
    network_mode: host
    volumes:
      - ./build/client:/client
      - ./build/server/scripts/certificates:/certificates
    depends_on:
      - server
    working_dir: /client
    command: bash -c "./scripts/registerCerts.sh & ./client.out"
